# Generated by Django 5.0.6 on 2024-05-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Url', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=500)),
                ('Item_Url', models.URLField()),
                ('Item_Price', models.CharField(max_length=50)),
                ('Item_Image_url', models.URLField()),
                ('Expected_Price', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
